name: Build and Release

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest-xlarge]

    steps:
      - name: Free Disk Space (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v3

      # Install required packets
      - name: Install ninja
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt-get -y install ninja-build

      - name: Install ninja
        if: matrix.os == 'macos-latest-xlarge'
        run: |
          brew install ninja

      # Clone things
      - name: Download Necessary sources
        run: ./clone.sh

      # Patch things
      - name: Apply patches
        run: ./patch.sh

      # Build Dists
      - name: Build dist
        run: ./build_dist.sh

      # Push in the Github environment variable the name of the artifact
      # Doing this now because in the following step the rust folder will be deleted to save some space before installing the toolchain
      - run: ./config.sh -artifact_name

      # Build Toolchain
      - name: Build Toolchain
        run: ./build_toolchain.sh

      # Create release
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.ARTIFACT_NAME }}.tar.xz"
          tag: "${{ env.ARTIFACT_NAME }}"
          name: "${{ env.ARTIFACT_NAME }}"
